# Prometheus config for VokeTag
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "scan-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["scan-service:8080"]

  - job_name: "factory-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["factory-service:8080"]

  - job_name: "admin-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["admin-service:8080"]

  - job_name: "blockchain-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["blockchain-service:8003"]
